export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  safelist: [
    { pattern: /^from-(stone|amber|red|violet|purple|fuchsia|rose|orange|emerald|sky|indigo|slate|zinc|neutral|blue)-(\d+)$/ },
    { pattern: /^via-(stone|amber|red|violet|purple|fuchsia|rose|orange|emerald|sky|indigo|slate|zinc|neutral|blue)-(\d+)$/ },
    { pattern: /^to-(stone|amber|red|violet|purple|fuchsia|rose|orange|emerald|sky|indigo|slate|zinc|neutral|blue)-(\d+)$/ },
  ],
  theme: {
    extend: {
      colors: {
        'bg-base': 'var(--bg-base)',
        'bg-surface': 'var(--bg-surface)',
        'bg-elevated': 'var(--bg-elevated)',
        'bg-elevated-soft': 'var(--bg-elevated-soft)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        'text-on-accent': 'var(--text-on-accent)',
        'border-subtle': 'var(--border-subtle)',
        'border-strong': 'var(--border-strong)',
        'border-faint': 'var(--border-faint)',
        'track': 'var(--track)',
        'track-faint': 'var(--track-faint)',
        'accent': 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-soft': 'var(--accent-soft)',
        'status-success': 'var(--status-success)',
        'status-error': 'var(--status-error)',
        'status-warning': 'var(--status-warning)',
        'status-warning-soft': 'var(--status-warning-soft)',
        'status-warning-border': 'var(--status-warning-border)',
        'status-info': 'var(--status-info)',
        'glass':                'var(--glass-bg)',
        'glass-strong':         'var(--glass-bg-strong)',
        'glass-ultra':          'var(--glass-bg-ultra)',
        'glass-tinted':         'var(--glass-bg-tinted)',
        'glass-border':         'var(--glass-border)',
        'glass-border-strong':  'var(--glass-border-strong)',
        'glass-highlight':      'var(--glass-highlight)',
        'glass-edge-dim':       'var(--glass-edge-dim)',
      },
      boxShadow: {
        'z1':            'var(--shadow-z1)',
        'z2':            'var(--shadow-z2)',
        'z3':            'var(--shadow-z3)',
        'glow-accent':   'var(--shadow-glow-accent)',
        'pill-active':   'var(--shadow-pill-active)',
        'glass-inner':   'var(--glass-inner-glow)',
      },
      backdropBlur: {
        'glass':       '20px',
        'glass-heavy': '32px',
        'glass-ultra': '48px',
      },
      backdropSaturate: {
        'liquid': '1.6',
      },
      boxShadow: {
      },
      transitionTimingFunction: {
        'depth': 'cubic-bezier(0.22, 1, 0.36, 1)',
        'smooth': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
      fontFamily: {
        sans:    ['Manrope', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['Unbounded', 'Manrope', 'system-ui', '-apple-system', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
