<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>gunpack</AssemblyName>
    <RootNamespace>MiamiGraphics.Gunpack</RootNamespace>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MiamiGraphics.Core\MiamiGraphics.Core.csproj" />
    <ProjectReference Include="..\CodeWalker.Core\CodeWalker.Core.csproj" />
  </ItemGroup>
</Project>
